### ISSUE TITLE
Windows environments

### ISSUE THREAD

**Issue by ocefpaf** [kwmsmith/scipy-2017-cython-tutorial#8]
Some people that are having trouble creating the Windows env, this may help:

```yaml
name: cython
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.5
  - beautifulsoup4
  - bkcharts
  - bleach
  - bokeh
  - ca-certificates
  - certifi
  - chardet
  - click
  - cloudpickle
  - cycler
  - cython
  - dask
  - decorator
  - dill
  - distributed
  - entrypoints
  - fastcache
  - freetype
  - h5py
  - hdf5
  - heapdict
  - html5lib
  - idna
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - libpng
  - libsodium
  - libtiff
  - llvmlite
  - locket
  - markupsafe
  - matplotlib
  - mistune
  - mpmath
  - msgpack-python
  - nbconvert
  - nbformat
  - networkx
  - nomkl
  - notebook
  - numba
  - numexpr
  - numpy
  - openssl
  - pandas
  - pandoc
  - pandocfilters
  - partd
  - patsy
  - pexpect
  - pickleshare
  - pillow
  - pip
  - prompt_toolkit
  - psutil
  - pygments
  - pyparsing
  - python-dateutil
  - pytz
  - pyyaml
  - pyzmq
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - simplegeneric
  - six
  - sortedcontainers
  - sqlalchemy
  - sqlite
  - statsmodels
  - sympy
  - tblib
  - testpath
  - tk
  - toolz
  - tornado
  - traitlets
  - urllib3
  - vincent
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xlrd
  - xz
  - yaml
  - zeromq
  - zict
  - zlib
  - mingwpy
  - pip:
    - appnope
```

Use it with `conda env create --file environment.yml --name cython-tutorial`

PS: You'll probably need Visual Studio 2015 for this tutorial.

You may need https://github.com/cython/cython/wiki/CythonExtensionsOnWindows
